### PR TITLE
Bugfix/create offer exceeding amount threshold

### LINKED ISSUE #71: Integration tests for amount exceeding account threshold
Creating offer with amount of 1btc results in 500 error and message
>An error occurred at task: ValidateOffer↵Exception message: Amount is larger then 0.16 BTC

The status code should be 42X.

### PR DESCRIPTION
**Pull request by blabno**
Fixes #71

### CODE REVIEW

File: src/main/java/io/bisq/api/BisqProxy.java [hunk 1]
```diff
@@ -247,9 +249,11 @@ public Offer getOffer(String offerId) {
                 fundUsingBisqWallet,
                 transaction -> futureResult.complete(offer),
                 error -> {
-                    if (error.contains("Insufficient money")) {
+                    if (error.contains("Insufficient money"))
                         futureResult.completeExceptionally(new InsufficientMoneyException(error));
-                    } else
+                    else if (error.contains("Amount is larger then"))
```
Comment (mrosseel) [inline src/main/java/io/bisq/api/BisqProxy.java]: it should be 'Amount is larger than', so this will probably be fixed at one point or another, breaking this. 
We should be able to do this cleaner, but in the mean time it might be smart to leave the 'then' out of the string, less chance of it breaking due to a spell-corrector :)
